/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pb138.evidenceskladurestaurace;

import cz.muni.fi.pb138.evidenceskladurestaurace.model.IngredientsTableModel;
import cz.muni.fi.pb138.evidenceskladurestaurace.model.RecipeListModel;
import cz.muni.fi.pb138.evidenceskladurestaurace.persistence.Ingredient;
import cz.muni.fi.pb138.evidenceskladurestaurace.persistence.IngredientDAO;
import cz.muni.fi.pb138.evidenceskladurestaurace.persistence.Recipe;
import cz.muni.fi.pb138.evidenceskladurestaurace.persistence.RecipeDAO;
import cz.muni.fi.pb138.evidenceskladurestaurace.persistence.RecipeDAOImpl;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Adams
 */
public class ReceiptDialog extends javax.swing.JFrame {

    private Recipe receipt;
    private RecipeDAO receiptDao;
    private RecipeListModel receiptListModel;
    private Boolean createNew = true;
    /**
     * Creates new form IngredientDialog
     */
    public ReceiptDialog(RecipeListModel receiptListModel, RecipeDAO receiptDao) {
        initComponents();
        this.receiptListModel = receiptListModel;
        this.receiptDao = receiptDao;
        setLocationRelativeTo(null);
        receipt = new Recipe();
    }

    public ReceiptDialog(RecipeListModel receiptListModel, RecipeDAO receiptDao, Recipe receipt) {
        initComponents();
        this.receipt = receipt;
        this.receiptListModel = receiptListModel;
        this.receiptDao = receiptDao;
        setLocationRelativeTo(null);

        createNew = false;

        receiptLabel.setText("Edit Receipt");
        receiptName.setText(receipt.getName());

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        receiptName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addIngredientButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        receiptLabel = new javax.swing.JLabel();
        ingredientsPanel = new javax.swing.JPanel();
        ingredientPanel = new javax.swing.JPanel();
        ingredientNameCombo = new javax.swing.JComboBox();
        ingredientAmount = new javax.swing.JTextField();
        ingredientUnit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Receipt Name:");

        jLabel2.setText("Ingredients :");

        addIngredientButton.setText("Add Ingedient");
        addIngredientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIngredientButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingredient name");

        jLabel4.setText("Amount");

        jLabel5.setText("Unit");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        receiptLabel.setText("Create new Receipt");

        ingredientNameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ingredientAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientAmountActionPerformed(evt);
            }
        });

        ingredientUnit.setText("unitName");

        org.jdesktop.layout.GroupLayout ingredientPanelLayout = new org.jdesktop.layout.GroupLayout(ingredientPanel);
        ingredientPanel.setLayout(ingredientPanelLayout);
        ingredientPanelLayout.setHorizontalGroup(
            ingredientPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ingredientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(ingredientNameCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 186, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ingredientAmount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(ingredientUnit)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        ingredientPanelLayout.setVerticalGroup(
            ingredientPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, ingredientPanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(ingredientPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ingredientNameCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ingredientAmount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ingredientUnit))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout ingredientsPanelLayout = new org.jdesktop.layout.GroupLayout(ingredientsPanel);
        ingredientsPanel.setLayout(ingredientsPanelLayout);
        ingredientsPanelLayout.setHorizontalGroup(
            ingredientsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ingredientsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(ingredientPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ingredientsPanelLayout.setVerticalGroup(
            ingredientsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ingredientsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(ingredientPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(234, 234, 234)
                .add(receiptLabel)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(37, 37, 37)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel2))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 26, Short.MAX_VALUE)
                        .add(ingredientsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(34, 34, 34))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(42, 42, 42)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(receiptName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 288, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(layout.createSequentialGroup()
                                        .add(jLabel3)
                                        .add(96, 96, 96)
                                        .add(jLabel4)
                                        .add(63, 63, 63)
                                        .add(jLabel5))))
                            .add(layout.createSequentialGroup()
                                .add(17, 17, 17)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(saveButton)
                                        .add(43, 43, 43)
                                        .add(cancelButton))
                                    .add(addIngredientButton))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(receiptLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(receiptName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(jLabel5))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jLabel2)
                        .add(213, 213, 213))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ingredientsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)))
                .add(addIngredientButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 27, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(saveButton)
                    .add(cancelButton))
                .add(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingredientAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredientAmountActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        receipt.setName(receiptName.getText());

        if(createNew){
            receiptDao.create(receipt);
        } else {
            receiptDao.update(receipt);
        }

        receiptListModel.setRecipes(receiptDao.findAll());

        dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void addIngredientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIngredientButtonActionPerformed
        ingredientsPanel.setLayout(new BoxLayout(ingredientsPanel, BoxLayout.Y_AXIS));

        JComboBox newIngredientName = new JComboBox();
        newIngredientName.add(ingredientNameCombo);

        JTextField newIngredientAmount = new JTextField();
        newIngredientAmount.add(ingredientAmount);

        JLabel newIngredientUnit = new JLabel();
        newIngredientUnit.add(ingredientUnit);

        JPanel newPanel = new JPanel();
        newPanel.add(newIngredientName);
        newPanel.add(newIngredientAmount);
        newPanel.add(newIngredientUnit);

        ingredientsPanel.add(newPanel);

        ingredientsPanel.revalidate();


        // TODOOOOO :
        // http://stackoverflow.com/questions/15127056/dynamic-adding-jpanel-to-another-jpanel-in-java-swing
//        ingredientsPanel.repaint();



    }//GEN-LAST:event_addIngredientButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addIngredientButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField ingredientAmount;
    private javax.swing.JComboBox ingredientNameCombo;
    private javax.swing.JPanel ingredientPanel;
    private javax.swing.JLabel ingredientUnit;
    private javax.swing.JPanel ingredientsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel receiptLabel;
    private javax.swing.JTextField receiptName;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
